language: php

matrix:
  include:
    - php: 5.3
      dist: precise

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls:0.* --dev
  - composer install --dev --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v -c .coveralls.yml
